version: '3'
services:
  mongodb:
    build:
      context: mongodb
    restart: always
    volumes:
      - $MONGODB_DATA_VOLUME:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DATABASE
      MONGO_NON_ROOT_USERNAME: $MONGO_NON_ROOT_USERNAME
      MONGO_NON_ROOT_PASSWORD: $MONGO_NON_ROOT_PASSWORD
    expose:
      - 27017
      - 27018
      - 27019

  # mongo-express:
  #   image: mongo-express:0.49.0
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGODB_USERNAME
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGODB_PASSWORD

  fluentd:
    build:
      context: fluentd
    restart: always
    volumes:
      - $FLUENTD_CONFIG_DIR:/fluentd/etc
    command: -v
    environment:
      FLUENTD_APP: $FLUENTD_APP
      MONGO_DATABASE: $MONGO_DATABASE
      MONGO_COLLECTION: $MONGO_COLLECTION
      MONGO_NON_ROOT_USERNAME: $MONGO_NON_ROOT_USERNAME
      MONGO_NON_ROOT_PASSWORD: $MONGO_NON_ROOT_PASSWORD
    depends_on:
      - mongodb
    expose:
      - 24224
    
  txlogging:
    build: .
    restart: always
    depends_on:
      - fluentd
      - mongodb
    environment:
      FLUENTD_HOST: fluentd
      FLUENTD_PORT: 24224
      FLUENTD_APP: $FLUENTD_APP
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: $MONGO_DATABASE
      MONGO_COLLECTION: $MONGO_COLLECTION
      MONGO_NON_ROOT_USERNAME: $MONGO_NON_ROOT_USERNAME
      MONGO_NON_ROOT_PASSWORD: $MONGO_NON_ROOT_PASSWORD
    ports:
      - $API_PORT:8080

    
