version: '3'
services:
  txlogging-mongodb:
    image: txscience/tx-persistence:latest
    restart: always
    volumes:
      - ${MONGODB_DATA_VOLUME}:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_NON_ROOT_USERNAME: ${MONGO_NON_ROOT_USERNAME}
      MONGO_NON_ROOT_PASSWORD: ${MONGO_NON_ROOT_PASSWORD}

  txlogging-fluentd:
    image: txscience/tx-fluetd:latest
    environment:
      FLUENTD_APP: ${FLUENTD_APP}
      MONGO_HOST: ${MONTO_HOST}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_COLLECTION: ${MONGO_COLLECTION}
      MONGO_NON_ROOT_USERNAME: ${MONGO_NON_ROOT_USERNAME}
      MONGO_NON_ROOT_PASSWORD: ${MONGO_NON_ROOT_PASSWORD}
    depends_on:
      - txlogging-mongodb
    
  txlogging:
    build: .
    restart: always
    depends_on:
      - txlogging-fluentd
      - txlogging-mongodb
    environment:
      FLUENTD_HOST: txlogging-fluentd
      FLUENTD_PORT: 24224
      FLUENTD_APP: ${FLUENTD_APP}
      MONGO_HOST: txlogging-mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_COLLECTION: ${MONGO_COLLECTION}
      MONGO_NON_ROOT_USERNAME: ${MONGO_NON_ROOT_USERNAME}
      MONGO_NON_ROOT_PASSWORD: ${MONGO_NON_ROOT_PASSWORD}
    ports:
      - ${API_PORT}:8080

