version: '3'
services:
  txlogging-mongodb:
    image: txscience/tx-persistence:latest
    restart: always
    volumes:
      - ${MONGODB_DATA_VOLUME}:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_NON_ROOT_USERNAME: ${MONGO_NON_ROOT_USERNAME}
      MONGO_NON_ROOT_PASSWORD: ${MONGO_NON_ROOT_PASSWORD}

  txlogging-fluentd:
    image: txscience/tx-fluentd:latest
    restart: always
    volumes:
      - ${FLUENTD_CONFIG_DIR}:/fluentd/etc
    environment:
      FLUENTD_APP: ${FLUENTD_APP}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_COLLECTION: ${MONGO_COLLECTION}
      MONGO_NON_ROOT_USERNAME: ${MONGO_NON_ROOT_USERNAME}
      MONGO_NON_ROOT_PASSWORD: ${MONGO_NON_ROOT_PASSWORD}
    depends_on:
      - txlogging-mongodb
    
  txlogging:
    build: .
    restart: always
    depends_on:
      - txlogging-fluentd
      - txlogging-mongodb
    environment:
      FLUENTD_HOST: ${FLUENTD_HOST}
      FLUENTD_PORT: ${FLUENTD_PORT}
      FLUENTD_APP: ${FLUENTD_APP}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_COLLECTION: ${MONGO_COLLECTION}
      MONGO_NON_ROOT_USERNAME: ${MONGO_NON_ROOT_USERNAME}
      MONGO_NON_ROOT_PASSWORD: ${MONGO_NON_ROOT_PASSWORD}
    ports:
      - $API_PORT:8080
