version: '3'
services:
  sut:
    build:
      context: test
    command: ["-s", "-x"]
    depends_on:
      - txlogging
      - txlogging-fluentd
      - txlogging-mongodb

  txlogging:
    build: .
    restart: always
    depends_on:
      - txlogging-fluentd
      - txlogging-mongodb
    environment:
      FLUENTD_HOST: txlogging-fluentd
      FLUENTD_PORT: 24224
      FLUENTD_APP: $FLUENTD_APP
      MONGO_HOST: txlogging-mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: $MONGO_DATABASE
      MONGO_COLLECTION: $MONGO_COLLECTION
      MONGO_NON_ROOT_USERNAME: $MONGO_NON_ROOT_USERNAME
      MONGO_NON_ROOT_PASSWORD: $MONGO_NON_ROOT_PASSWORD
    ports:
      - $API_PORT:8080

  txlogging-fluentd:
    build:
      context: fluentd
    restart: always
    volumes:
      - $FLUENTD_CONFIG_DIR:/fluentd/etc
    environment:
      FLUENTD_APP: $FLUENTD_APP
      MONGO_HOST: txlogging-mongodb
      MONGO_DATABASE: $MONGO_DATABASE
      MONGO_COLLECTION: $MONGO_COLLECTION
      MONGO_NON_ROOT_USERNAME: $MONGO_NON_ROOT_USERNAME
      MONGO_NON_ROOT_PASSWORD: $MONGO_NON_ROOT_PASSWORD
    depends_on:
      - txlogging-mongodb

  txlogging-mongodb:
    image: tx-persistence
    restart: always
    volumes:
      - $MONGODB_DATA_VOLUME:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DATABASE
      MONGO_NON_ROOT_USERNAME: $MONGO_NON_ROOT_USERNAME
      MONGO_NON_ROOT_PASSWORD: $MONGO_NON_ROOT_PASSWORD

volumes:
  txlogging-mongo-data:
    driver: local
