version: '3'
services:
  sut:
    build:
      context: .
      dockerfile: test/Dockerfile
    command: ["-s", "-x"]
    depends_on:
      - txlogging
      - txlogging-fluentd
      - txlogging-mongodb

  txlogging-mongodb:
    image: txscience/tx-persistence:latest
    restart: always
    volumes:
      - txlogging-mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: txloggingdb
      MONGO_NON_ROOT_USERNAME: txlogging
      MONGO_NON_ROOT_PASSWORD: log

  txlogging-fluentd:
    image: txscience/tx-fluentd:latest
    restart: always
    volumes:
      - ../build/fluentd/etc:/fluentd/etc
    environment:
      FLUENTD_APP: txlogging
      MONGO_HOST: txlogging-mongodb
      MONGO_DATABASE: txloggingdb
      MONGO_COLLECTION: log
      MONGO_NON_ROOT_USERNAME: txlogging
      MONGO_NON_ROOT_PASSWORD: log
    depends_on:
      - txlogging-mongodb

# doesnt work:
#      - ../build/fluentd/etc:/fluentd/etc

  txlogging:
    build: .
    restart: always
    depends_on:
      - txlogging-fluentd
      - txlogging-mongodb
    environment:
      FLUENTD_HOST: txlogging-fluentd
      FLUENTD_PORT: 24224
      FLUENTD_APP: txlogging
      MONGO_HOST: txlogging-mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: txloggingdb
      MONGO_COLLECTION: log
      MONGO_NON_ROOT_USERNAME: txlogging
      MONGO_NON_ROOT_PASSWORD: log
    ports:
      - 8080:8080

volumes:
  txlogging-mongo-data:
    driver: local
