openapi: 3.0.0
info:
  description: |
    This is a sample logging server.
  version: "1.0.0"
  title: txlogging
tags:
  - name: logging
    description: logging
paths:
  /log:
    post:
      tags:
        - logging
      summary: Add a log entry
      operationId: api.postLog
      responses:
        '200':
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Log'
    get:
      tags:
        - logging
      summary: get log entries
      description: get log entries
      operationId: api.getLog
      parameters:
        - name: start
          in: query
          description: start
          schema:
            type: string
            format: date-time
        - name: end
          in: query
          description: end
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: successful operation
          content:
            application/x-ndjson:
              schema: {}
        '400':
          description: Invalid value
    delete:
      tags:
        - logging
      summary: get log entries
      description: get log entries
      operationId: api.deleteLog
      responses:
        '200':
          description: successful operation
components:
  schemas:
    Log:
      type: object
      properties:
        _id:
          not: {}
        timestamp:
          type: string
          format: date-time
        event:
          type: string
        source:
          type: string
        level:
          type: string
      required: ["timestamp", "event", "source", "level"]
